# Generated by Django 6.0.3 on 2026-05-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_simulation_transaction_voucher_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AShareStock',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('name', models.CharField(max_length=100, verbose_name='股票名称')),
                ('market', models.CharField(max_length=4, verbose_name='市场(SH/SZ/BJ)')),
                ('market_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='板块类型')),
                ('total_market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='总市值(元)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'A股股票',
                'verbose_name_plural': 'A股股票',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='AShareRealtimePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, verbose_name='股票代码')),
                ('name', models.CharField(max_length=100, verbose_name='股票名称')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='最新价')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='开盘价')),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='最高价')),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='最低价')),
                ('pre_close', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='昨收价')),
                ('volume', models.BigIntegerField(default=0, verbose_name='成交量(手)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='成交额')),
                ('change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='涨跌幅(%)')),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市盈率')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': 'A股实时行情',
                'verbose_name_plural': 'A股实时行情',
                'indexes': [models.Index(fields=['symbol'], name='stock_ashar_symbol_8489d5_idx'), models.Index(fields=['-change_pct'], name='stock_ashar_change__7eb927_idx')],
            },
        ),
    ]
