# Generated by Django 6.0.3 on 2026-05-25 11:40

import django.db.models.deletion
from django.db import migrations, models


def copy_company_to_asharestock(apps, schema_editor):
    """
    将 stock_company 表中的所有数据复制到 stock_asharestock，
    确保后续 FK 变更不会因数据缺失而失败。
    """
    Company = apps.get_model('stock', 'Company')
    AShareStock = apps.get_model('stock', 'AShareStock')

    for c in Company.objects.all():
        AShareStock.objects.update_or_create(
            symbol=c.symbol,
            defaults={
                'name': c.full_name,
                'industry': c.industry,
                'market': 'US',  # CSV 导入的美股标记为 US
                'market_type': c.industry.sector if c.industry else '',
                'total_market_cap': int(c.market_cap) if c.market_cap else None,
                'trailing_pe': c.trailing_pe,
                'price_sales': c.price_sales,
                'current_price': c.current_price,
            }
        )
    print(f"  ✓ 已将 {Company.objects.count()} 条 Company 数据迁移到 AShareStock")


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_asharestock_asharerealtimeprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asharestock',
            options={'ordering': ['symbol'], 'verbose_name': '股票', 'verbose_name_plural': '股票'},
        ),
        migrations.AddField(
            model_name='asharestock',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='最新价'),
        ),
        migrations.AddField(
            model_name='asharestock',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_stocks', to='stock.industry', verbose_name='所属行业'),
        ),
        migrations.AddField(
            model_name='asharestock',
            name='price_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市销率'),
        ),
        migrations.AddField(
            model_name='asharestock',
            name='trailing_pe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市盈率'),
        ),
        # === 关键步骤：先把 Company 数据复制到 AShareStock，再改 FK ===
        migrations.RunPython(copy_company_to_asharestock, reverse_code=migrations.RunPython.noop),
        # === FK 变更 ===
        migrations.AlterField(
            model_name='dailyprice',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stock.asharestock'),
        ),
        migrations.AlterField(
            model_name='financials',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stock.asharestock'),
        ),
        migrations.AlterField(
            model_name='simulation_holding',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.asharestock'),
        ),
        migrations.AlterField(
            model_name='simulation_transaction',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.asharestock'),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.asharestock'),
        ),
    ]
